### ISSUE TITLE
告警页面建议增加两个功能

### ISSUE THREAD

**Issue by a1007479270** [nezhahq/nezha#476]
使用哪吒的小白也比较多
一、增加常用推送渠道 
比如pushplus 推送加 、bark、server 酱等  
使用者只需要填写key就行

二、增加常用告警规则模板
比如流量预警、硬盘预警、cpu内存预警等

**Comment by a1007479270** [comment]
![11b394e93775f2ecfe404bac1ec3641](https://github.com/user-attachments/assets/f379afcc-7101-4b79-a314-9f3802d32f50)
![1731567250096](https://github.com/user-attachments/assets/c054d1ff-3b79-43a5-8310-751e6ee419c3)

**Comment by a1007479270** [comment]
> 通知渠道的配置文档中有demo 规则目前文档中也提供了第三方生成器

我想表达的是简化流程，提高用户体验，内置几项常用的规则 而不需要重新打开网页查找资料。而更深入的使用 那肯定是需要查找文档。

**Comment by uubulb** [comment]
没必要，加了一个预设就会有人去建议加更多的预设
