### ISSUE TITLE
[BUG?]1.0客户端离线后前端要等5分钟左右才显示离线

### ISSUE THREAD

**Issue by molehzy** [nezhahq/nezha#491]
dashboard版本1.0.3
user-frontend版本1.0.3
admin-frontend版本1.0.4
agent版本1.0.0

![{A1C52DE6-561A-43E6-8FCC-1712B6A12342}](https://github.com/user-attachments/assets/15911688-d3e3-40fb-b77d-7a404fb4f2ad)
![{D70619FD-423D-44D4-9445-53FD21CC5726}](https://github.com/user-attachments/assets/bce3cc97-8300-4c4c-9b8b-84e3efb6ee64)

**Comment by naiba** [comment]
请提到 https://github.com/hamster1963/nezha-dash-react
