### ISSUE TITLE
V1版本探针安装后不小心执行了两次会有两个同时存在的监控节点

### ISSUE THREAD

**Issue by TakakiAnber** [nezhahq/nezha#498]
V1版本探针安装后不小心执行了两次，主控会显示有两个同时存在的监控节点
怎么删除掉其中一个？
在主控上面删除不了，刷新后又出现显示，去被控的主机kill掉进程也不行
有没有专门卸载被控端的脚本？还是直接删除agent的文件夹即可？

**Comment by dyit-dalanmao** [comment]
我也需要这个 我靠 蹦出来一堆

**Comment by uubulb** [comment]
duplicate of https://github.com/nezhahq/scripts/issues/18.
