### ISSUE TITLE
NeZha老版本链接保留

### ISSUE THREAD

**Issue by Michaelwucoc** [nezhahq/nezha#500]
我现在无法添加任何新的服务器, Linux勉强可以通过备用链接下载
```
curl -L https://gitee.com/gaimoy/hwid-qq/raw/master/script/install.sh -o nezha.sh && chmod +x nezha.sh && ./nezha.sh install_agent xxx 5555 xxx
```
但是现在Windows服务器直接罢工
![image](https://github.com/user-attachments/assets/680c0ad0-45d8-44e1-82c1-64a5c293e026)

能否保留老版本下载链接? 谢谢!

**Comment by Michaelwucoc** [comment]
:(

**Comment by uubulb** [comment]
windows 可以手动添加，windows脚本就干了2个事，下载并运行内置服务命令。

**Comment by Michaelwucoc** [comment]
好的
