### ISSUE TITLE
运行最新版本docker镜像log显示open translations/auto/LC_MESSAGES/nezha.po: file does not exist 反复重启

### ISSUE THREAD

**Issue by muzihuaner** [nezhahq/nezha#517]
2024/12/01 17:35:11 NEZHA>> init i18n failed: open translations/auto/LC_MESSAGES/nezha.po: file does not exist
2024/12/01 17:35:11 NEZHA>> Dashboard::START 8008
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc8c546]

goroutine 22 [running]:
github.com/nezhahq/nezha/pkg/i18n.(*Localizer).T(0x0, {0x11dfbee, 0x4})
	github.com/nezhahq/nezha/pkg/i18n/i18n.go:68 +0x26
github.com/nezhahq/nezha/service/singleton.StatusCodeToString(0x109e700?)
	github.com/nezhahq/nezha/service/singleton/servicesentinel.go:606 +0x3e
github.com/nezhahq/nezha/service/singleton.(*ServiceSentinel).worker(0xc0002400a0)
	github.com/nezhahq/nezha/service/singleton/servicesentinel.go:472 +0x1d4f
created by github.com/nezhahq/nezha/service/singleton.NewServiceSentinel in goroutine 1
	github.com/nezhahq/nezha/service/singleton/servicesentinel.go:75 +0x7af

**Comment by cnmars** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc8c546]

goroutine 55 [running]:
github.com/nezhahq/nezha/pkg/i18n.(*Localizer).T(0x0, {0x11ec003, 0x8})
        github.com/nezhahq/nezha/pkg/i18n/i18n.go:68 +0x26
github.com/nezhahq/nezha/service/singleton.checkStatus()
        github.com/nezhahq/nezha/service/singleton/alertsentinel.go:159 +0x488
github.com/nezhahq/nezha/service/singleton.AlertSentinelStart()
        github.com/nezhahq/nezha/service/singleton/alertsentinel.go:81 +0x2bc
created by main.main in goroutine 1
        github.com/nezhahq/nezha/cmd/dashboard/main.go:124 +0x371

**Comment by zhonghuhe** [comment]
2024/12/01 22:15:03 NEZHA>> init i18n failed: open translations/zh-CN/LC_MESSAGES/nezha.po: file does not exist
2024/12/01 22:15:03 NEZHA>> Dashboard::START 8008
我也遇到了报错

**Comment by muzihuaner** [comment]
已解决
<img width="657" alt="image" src="https://github.com/user-attachments/assets/7a83844b-21d4-4b6d-b47d-23f2fbea8dc6">

**Comment by muzihuaner** [comment]
密钥指 agentsecretkey:  先备份一下
