### ISSUE TITLE
使用域名登录后台dashboard报错

### ISSUE THREAD

**Issue by qiuyesichen** [nezhahq/nezha#519]
使用ip+ 端口登陆没有问题，但反代后使用域名进入后台报错ApiErrorUnauthorized。另外，还有一个问题，就是可以在一台机器中安装多个Agent，机器会同时运行多个Agent进程，在后台显示多台机器。

**Comment by FreeyW** [comment]
我也遇到了这个问题，但是我不管是ip+端口还是域名都无法登录

**Comment by thun888** [comment]
我直接覆盖安装后也是这样，日志中显示找不到admin用户。我推测的是当数据表中已有用户时，不再新建管理员用户，但是新版内建了密码登录，新增了用户名和密码字段，而在迁移后这两者对应为空值，需要下载数据库文件手动修改

密码使用bcrypt加密，可以用 https://33tool.com/bcrypt/ 在线生成

数据库在 /opt/nezha/dashboard/data/ 
使用 `systemctl stop nezha-dashboard.service` 和 `systemctl start nezha-dashboard.service`启停服务

![image](https://github.com/user-attachments/assets/c16c933f-aa89-4d5f-a485-98121baddc7c)

**Comment by diyes** [comment]
> 我直接覆盖安装后也是这样，日志中显示找不到admin用户。我推测的是当数据表中已有用户时，不再新建管理员用户，但是新版内建了密码登录，新增了用户名和密码字段，而在迁移后这两者对应为空值，需要下载数据库文件手动修改
> 
> 密码使用bcrypt加密，可以用 https://33tool.com/bcrypt/ 在线生成
> 
> 数据库在 /opt/nezha/dashboard/data/ 使用 `systemctl stop nezha-dashboard.service` 和 `systemctl start nezha-dashboard.service`启停服务
> 
> ![image](https://private-user-images.githubusercontent.com/63234268/393503803-c16c933f-aa89-4d5f-a485-98121baddc7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjMyNDQsIm5iZiI6MTczMzgyMjk0NCwicGF0aCI6Ii82MzIzNDI2OC8zOTM1MDM4MDMtYzE2YzkzM2YtYWE4OS00ZDVmLWE0ODUtOTgxMjFiYWRkYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA5MjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMzg1NWM5MjczODA1N2Y1ODliYjM4OWNkZjk4ZTE5ZDAyZmExOWU5YjQ0MTc1YTI5ZDU5NjZiNmZiNzhjMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DVOOIkrjUMnTlRpawkc84qzK1rTbZpQwhry_lJ-M2D4)
感谢，问题解决。

**Comment by LevineWoo** [comment]
> > 我直接覆盖安装后也是这样，日志中显示找不到admin用户。我推测的是当数据表中已有用户时，不再新建管理员用户，但是新版内建了密码登录，新增了用户名和密码字段，而在迁移后这两者对应为空值，需要下载数据库文件手动修改
> > 密码使用bcrypt加密，可以用 https://33tool.com/bcrypt/ 在线生成
> > 数据库在 /opt/nezha/dashboard/data/ 使用 `systemctl stop nezha-dashboard.service` 和 `systemctl start nezha-dashboard.service`启停服务
> > ![image](https://private-user-images.githubusercontent.com/63234268/393503803-c16c933f-aa89-4d5f-a485-98121baddc7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjMyNDQsIm5iZiI6MTczMzgyMjk0NCwicGF0aCI6Ii82MzIzNDI2OC8zOTM1MDM4MDMtYzE2YzkzM2YtYWE4OS00ZDVmLWE0ODUtOTgxMjFiYWRkYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA5MjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMzg1NWM5MjczODA1N2Y1ODliYjM4OWNkZjk4ZTE5ZDAyZmExOWU5YjQ0MTc1YTI5ZDU5NjZiNmZiNzhjMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DVOOIkrjUMnTlRpawkc84qzK1rTbZpQwhry_lJ-M2D4)
> > 感谢，问题解决。

图挂了，可以请问下具体怎么操作嘛？

**Comment by LevineWoo** [comment]
> 解决步骤： 将 data 文件夹下数据库文件 sqlite.db 导出，手动将username/password两个字段按照如上的方式新增

我后来重新换了一台机器安装了。看了sqlite.db里的password和username都是有的，而且password也是符合bcrypt加密并校验成功的。但仍然有这个错误。
