### ISSUE TITLE
在一台VPS上运行了多个agent，如何删除多余的agent进程？

### ISSUE THREAD

**Issue by i80980** [nezhahq/nezha#523]
![image](https://github.com/user-attachments/assets/8feb3fbc-05ac-4ad5-8f25-5125f6f95f2e)
一直不显示，分别用root用户和普通用户运行了好几次agent脚本，重启服务器后全冒出来了。
这是在一台服务器上运行了多个agent吗？如何删除多余的agent？

**Comment by XKlsy** [comment]
在linux中查找跟agent相关的进程ps aux | grep -i agent | grep -v grep ，kill掉，然后进入/opt/nezha/agent里面，删掉所有config文件，然后，重新运行agent的相关命令

**Comment by i80980** [comment]
> 在linux中查找跟agent相关的进程ps aux | grep -i agent | grep -v grep ，kill掉，然后进入/opt/nezha/agent里面，删掉所有config文件，然后，重新运行agent的相关命令

感谢，我也找到个清理脚本
bash <(curl -fsSL https://raw.githubusercontent.com/leuxinovo/qingli/refs/heads/main/agent.sh)

**Comment by loohalh** [comment]
哈哈

**Comment by Cookrs** [comment]
bash <(curl -fsSL https://raw.githubusercontent.com/SimonGino/Config/master/sh/uninstall_nezha_agent.sh)

**Comment by uubulb** [comment]
duplicate of https://github.com/nezhahq/scripts/issues/18.

**Comment by a525850194** [comment]
感谢感谢
