### ISSUE TITLE
在iOS16的safari浏览器以及部分安卓浏览器上显示WebSocket连接中

### ISSUE THREAD

**Issue by yahuisme** [nezhahq/nezha#527]
目前已知在在iOS16的safari浏览器以及部分安卓浏览器上一直显示”WebSocket连接中“，
![1](https://github.com/user-attachments/assets/2b01b360-8006-48eb-9e6f-84fa054a0a62)
这个问题猜测出在开发端的WebSocket兼容性上。

**Comment by uubulb** [comment]
Please report at https://github.com/hamster1963/nezha-dash/issues,
