### ISSUE TITLE
字体显示缺块

### ISSUE THREAD

**Issue by wanyunr** [nezhahq/nezha#528]
### Environment

Windows 10

### Agent Version

v1.0.15

### Describe the bug

如图，默认主题的文字显示很奇怪，数字会缺角
平台：Windows 10，Edge浏览器，1080P显示屏，
![image](https://github.com/user-attachments/assets/e3048549-4f86-4267-8a11-0a04c7174c05)

### To Reproduce

<details>手机上没复现，可能是默认字体适配问题？</details>

### Additional Context

<details></details>

### Validation

- [X] I confirm this is a bug about nezha (Nezha Dashboard).
- [X] I have searched Issues and confirm this bug has been reported before.

**Comment by uubulb** [comment]
Please report at https://github.com/hamster1963/nezha-dash/issues,
