### ISSUE TITLE
能否给出Nginx Proxy Manager的反代配置

### ISSUE THREAD

**Issue by lingbaoboy** [nezhahq/nezha#533]
### 运行环境

docker Nginx Proxy Manager

### Agent 版本

1.0.2

### 描述问题

<details>目前wiki给出了nginx的反代设置，但是目前我的vps统一使用了Nginx Proxy Manager进行nginx管理，使用Nginx Proxy Manager设置后，工作正常，但是不知道是否安全，因此希望wiki给出一个使用Nginx Proxy Manager的建议配置</details>

### 复现步骤

<details>见上</details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by leohooho** [comment]
不需要特殊的设置的，NPM 支持ws的  也不需要增加location

**Comment by AshinLin** [comment]
反代管理页面不需要额外设置。但是grpc我一直不成功。
