### ISSUE TITLE
网络监控数据只记录24h有点短

### ISSUE THREAD

**Issue by lingbaoboy** [nezhahq/nezha#534]
### 运行环境

ubuntu 24.04

### Agent 版本

1.0.2

### 描述问题

<details></details>
节点网络监控图表只能显示24h，反馈前端，前端说官方只记录了24h的数据
网络监控24小时有点短，不能看出长期的网络变化，因此建议至少记录一个月的数据，当然如果用户可以选择一年就更好了

### 复现步骤

<details>如上</details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
现在的数据库存一个月甚至更长怕是不太行，其它的指标数据也不考虑记录

**Comment by lingbaoboy** [comment]
那能否允许一周，24小时确实短了点

**Comment by xihefeng** [comment]
> 现在的数据库存一个月甚至更长怕是不太行，其它的指标数据也不考虑记录

能否根据数量进行调整，例如我60秒上传一条数据，然后保存10000条，这样可以显示更长的数据范围，性能也影响不大
