### ISSUE TITLE
ReportSystemState 相关错误

### ISSUE THREAD

**Issue by Atomesh** [nezhahq/nezha#541]
### Environment

Linux 6.1.0-27-cloud-arm64 #1 SMP Debian 6.1.115-1 (2024-11-01) aarch64 GNU/Linux

### Nezha Version

v1.0.17

### Describe the bug

<details>

在 Dashboard 端出现错误提示
```bash
ReportSystemState eror: rpc error: code = Canceled desc = context canceled, clientID: 1
```

在 Agent 端出现错误提示
```bash
worker exit to main: reportStateDaemon exit: EOF
```

报错出现在 Agent 运行一分钟后回报数据的时候。
我无法确认这是 Dashboard 端还是 Agent 端的错误。
我使用了 Traefik 进行了反向代理，之所以将 rpc 单独拿出来，是因为直接使用 H2C 代理，前端会有 Websocket 连接中的 Bug。
```yaml
      - traefik.http.routers.${SERVICE_NAME}.entryPoints=web
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_NAME}.${DOMAIN_domain}.domain.com`)
      - traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=8008
      - traefik.http.routers.${SERVICE_NAME}-RPC.entryPoints=web
      - traefik.http.routers.${SERVICE_NAME}-RPC.rule=Host(`${SERVICE_NAME}-RPC.${DOMAIN_domain}.domain.com`)
      - traefik.http.routers.${SERVICE_NAME}-RPC.service=${SERVICE_NAME}-RPC
      - traefik.http.services.${SERVICE_NAME}-RPC.loadbalancer.server.port=8008
      - traefik.http.services.${SERVICE_NAME}-RPC.loadbalancer.server.scheme=h2c
```
</details>

### To Reproduce

<details>
Dashboard 使用 Docker 进行安装

Agent 使用命令行如下

```bash
curl -L https://raw.githubusercontent.com/nezhahq/scripts/main/agent/install.sh -o nezha.sh && chmod +x nezha.sh && env NZ_SERVER=xxxx:443 NZ_TLS=true NZ_CLIENT_SECRET=xxxx ./nezha.sh
```
</details>

### Additional Context

<details></details>

### Validation

- [ ] I confirm this is a bug about nezha (Nezha Dashboard).
- [X] I have searched Issues and confirm this bug has been reported before.

**Comment by uubulb** [comment]
由于我不使用这个反代软件，只能给你说下可能的原因：
有另外一个agent使用相同uuid连接了相同的dashboard，互相竞争就会导致这个问题

**Comment by Atomesh** [comment]
通过不反代，发现不是程序的问题，检查后发现了 Traefik 有个与 gRPC 相关的 Issue
https://github.com/traefik/traefik/issues/10991

简单来说，就是由于 Traefik 默认设置了超时时间为 60，因而 dashboard 维持的长连接会被中断
通过将 Traefik 的 readTimeout 设置为 0，可以解决这个问题
```
    transport:
      respondingTimeouts:
        readTimeout: 0
```

但我有点疑惑，nezha 的 gRPC 会维持多久的连接呢，我有点不想设置为 0，因为这样似乎会存在风险
能否麻烦 @uubulb 解惑，非常感谢

**Comment by uubulb** [comment]
https://github.com/nezhahq/nezha/pull/402

**Comment by uubulb** [comment]
This issue is considered resolved.
If you have further questions, feel free to open again!

**Comment by Atomesh** [comment]
> #402

抱歉，这个 PR 讲的似乎是 Terminal 这个功能相关的，而非 gRPC 相关的，我是想知道 gRPC 有可能会维持多久的连接，以便于我将超时时间设置得比连接时间高一点，或者设置为回报周期多一些

可能是我没法了解其中的意思，能否麻烦跟我稍微详细说明一下，给出关键词让我去查找也可以，多谢

**Comment by uubulb** [comment]
https://github.com/nezhahq/nezha/commit/be51c5a1e6c933da1b886a431873951dc75f8727 完善了保活机制，可以试一试

**Comment by Atomesh** [comment]
> [be51c5a](https://github.com/nezhahq/nezha/commit/be51c5a1e6c933da1b886a431873951dc75f8727) 完善了保活机制，可以试一试

更新后放置了几分钟，似乎没有在出现了，问题应该解决了，我现在关闭这个 issue 非常感谢
