### ISSUE TITLE
server address should not be empty

### ISSUE THREAD

**Issue by chowyuan1314** [nezhahq/nezha#542]
### 运行环境

debian 12.8

### Nezha 版本

1.?

### 描述问题

<details>使用curl -L https://raw.githubusercontent.com/nezhahq/scripts/refs/heads/main/install.sh -o nezha.sh && chmod +x nezha.sh && sudo ./nezha.sh安装了面板后，重新添加了7台服务器，几天后再次在服务端运行./nezha.sh时就出现init config failed: server address should not be empty这样的提示。
</details>

### 复现步骤

<details>直接在服务端运行./nezha.sh即可复现</details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by sorawub** [comment]
出现同样问题，使用服务端管理页面的一键添加脚本，在初次运行的时候五任何提示，返回面板发现未有服务器，此时客户端再次运行./nezha.sh出现以下错误：
root@debian:~# ./nezha.sh
Installing...
NZ_SERVER should not be empty
root@debian:~#
