### ISSUE TITLE
使用cloudflare cdn后面板时不时520

### ISSUE THREAD

**Issue by cciy** [nezhahq/nezha#546]
### 运行环境

Debian GNU/Linux 11

### Nezha 版本

Dashboard v1.0.18  Agent v1.0.2

### 描述问题

<details>使用最新版哪吒面板正常安装套cf cdn 后出现520</details>

### 复现步骤

nginx 配置如下：
`server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;  # 启用 HTTP/2

    server_name xxxx; # 替换为你的域名
    ssl_certificate          /etc/nginx/cert/xxxx.pem; # 域名证书路径
    ssl_trusted_certificate /etc/nginx/cert/origin_ca_rsa_root.pem;
    ssl_certificate_key      /etc/nginx/cert/xxxx.key;       # 域名私钥路径
    ssl_stapling on;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m; # 如果与其他配置冲突，请注释此项
    ssl_protocols TLSv1.2 TLSv1.3;
        # HSTS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    underscores_in_headers on;
    set_real_ip_from 0.0.0.0/0; # 替换为你的 CDN 回源 IP 地址段
    real_ip_header CF-Connecting-IP; # 替换为你的 CDN 提供的私有 header，此处为 CloudFlare 默认
    # 如果你使用nginx作为最外层，把上面两行注释掉

    # grpc 相关    
    location ^~ /proto.NezhaService/ {
        grpc_set_header Host $host;
        grpc_set_header nz-realip $http_CF_Connecting_IP; # 替换为你的 CDN 提供的私有 header，此处为 CloudFlare 默认
        # grpc_set_header nz-realip $remote_addr; # 如果你使用nginx作为最外层，就把上面一行注释掉，启用此行
        grpc_read_timeout 600s;
        grpc_send_timeout 600s;
        grpc_socket_keepalive on;
        client_max_body_size 10m;
        grpc_buffer_size 4m;
        grpc_pass grpc://dashboard;
    }
    # websocket 相关
    location ~* ^/api/v1/ws/(server|terminal|file)(.*)$ {
        proxy_set_header Host $host;
        proxy_set_header nz-realip $http_cf_connecting_ip; # 替换为你的 CDN 提供的私有 header，此处为 CloudFlare 默认
        # proxy_set_header nz-realip $remote_addr; # 如果你使用nginx作为最外层，就把上面一行注释掉，启用此行
        proxy_set_header Origin https://$host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_pass http://dashboard;
    }
    # web
    location / {
        proxy_set_header Host $host;
        proxy_set_header nz-realip $http_cf_connecting_ip; # 替换为你的 CDN 提供的私有 header，此处为 CloudFlare 默认
        # proxy_set_header nz-realip $remote_addr; # 如果你使用nginx作为最外层，就把上面一行注释掉，启用此行
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
        proxy_max_temp_file_size 0;
        proxy_pass http://dashboard;
    }
   # proxy_set_header X-Forwarded-Proto https; 
}

upstream dashboard {
    server localhost:8008;
    keepalive 512;
}`
tls 为 true
后台配置如下：
![houtai](https://github.com/user-attachments/assets/9642fb57-cde3-4e42-b982-7850c32e927a)

请求错误如下：
![yemian](https://github.com/user-attachments/assets/13752550-3cec-4315-a648-181408915e5c)
![request](https://github.com/user-attachments/assets/62c381d3-78fe-42c4-8f56-96e83948ff3d)

nginx 错误如下：

`2024/12/04 13:10:48 [error] 15640#15640: *25062 upstream sent no valid HTTP/1.0 header while reading response header from upstream, client`

### 附加信息

<details></details>
无

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
反代问题，可以尝试加入 `proxy_http_version 1.1;`
或者干脆使用其它反代软件，比如 `caddy`，有报告说使用 `caddy` 后类似情况的出现率很低。

**Comment by cciy** [comment]
> 反代问题，可以尝试加入 `proxy_http_version 1.1;` 或者干脆使用其它反代软件，比如 `caddy`，有报告说使用 `caddy` 后类似情况的出现率很低。

已经加上proxy_http_version 1.1; 还是一样的。 其他人有改好nginx 配置出现概率低一点的吗？我之前用Dashboard v1.0.16没有带端口的时候反代是正常的。。。。

**Comment by uubulb** [comment]
我也试了下
非grpc的不要用 `http://dashboard`，改成`http://127.0.0.1:8008`，基本上没520了

**Comment by fhb302** [comment]
我采用Caddy也是一样的，报520错误，显示重定向次数过多
