### ISSUE TITLE
新版agent通信使用的client_secret和client_uuid会被nginx作为非法头部直接丢弃

### ISSUE THREAD

**Issue by wyx2685** [nezhahq/nezha#549]
### 运行环境

Ubuntu 24

### Nezha 版本

v1.0.20

### 描述问题

使用nginx转发agent的grpc流量时，需要添加 ignore_invalid_headers off; 选项，并添加以下header，否则无法连接成功

```
            grpc_set_header client_secret $http_client_secret;
            grpc_set_header client_uuid $http_client_uuid;
```

### 复现步骤

nginx配置示例

```
        #ignore_invalid_headers off;
        location /proto.NezhaService {
            #ignore_invalid_headers off;
            real_ip_header CF-Connecting-IP;
            grpc_set_header Connection "";
            grpc_set_header client_secret $http_client_secret;
            grpc_set_header client_uuid $http_client_uuid;
            grpc_pass grpc://127.0.0.1:8008;

         }
```

### 附加信息

可能需要改成用client-secret和client-uuid 

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
可以尝试添加 `underscores_in_headers on;`。

**Comment by wyx2685** [comment]
> 可以尝试添加 `underscores_in_headers on;`。

也有效，这个不改的话可能只能文档着重提醒了

**Comment by uubulb** [comment]
> > 可以尝试添加 `underscores_in_headers on;`。
> 
> 也有效，这个不改的话可能只能文档着重提醒了

文档目前反代配置是有这个参数的，可以加faq里
