### ISSUE TITLE
agetn1.2 面板最新版本无法获取IP

### ISSUE THREAD

**Issue by boyyadi** [nezhahq/nezha#553]
### 运行环境

Debian 12

### Nezha 版本

1021

### 描述问题

![image.png](https://s2.loli.net/2024/12/05/yxKlmPuCavDokMb.png)

### 复现步骤

升级及可

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
把你的 agent 更新到最新版本。
