### ISSUE TITLE
服务中显示：选择是否向游客显示此监控（隐私性选项）。新版本是不是失效了？  关闭的情况下  管理员也看不到了

### ISSUE THREAD

**Issue by chrisvorer6** [nezhahq/nezha#560]
### 运行环境

Debian 12

### Nezha 版本

1.0.22

### 描述问题

<details>服务中显示：选择是否向游客显示此监控（隐私性选项）。新版本是不是失效了？  关闭的情况下  管理员也看不到了</details>

### 复现步骤

<details></details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
和 v0 保持一致，原先的行为纯属意外，抱歉。
