### ISSUE TITLE
新版本无法添加服务器

### ISSUE THREAD

**Issue by yuehun** [nezhahq/nezha#562]
### Environment

linux

### Nezha Version

1.0.22

### Describe the bug

没有旧版本添加服务器按钮，选择安装命令安装以后列表里面也没有出现![image](https://github.com/user-attachments/assets/a20c459f-e34e-4657-8095-a37f605a192e)

### To Reproduce

<details></details>
没有旧版本添加服务器按钮，选择安装命令安装以后列表里面也没有出现![image](https://github.com/user-attachments/assets/a20c459f-e34e-4657-8095-a37f605a192e)

### Additional Context

<details></details>

### Validation

- [X] I confirm this is a bug about nezha (Nezha Dashboard).
- [X] I have searched Issues and confirm this bug has been reported before.

**Comment by yuehun** [comment]
端口使用的是8008

**Comment by yuehun** [comment]
我装了1.0.18版本的是可以正常添加的

**Comment by laulzgoay** [comment]
设置选项中“Agent 使用 TLS 连接”是不是开启的？我试过如果通过TLS连接，好像不可以，此行正想来查找ISSUE中是否有解决方案

**Comment by yuehun** [comment]
> 设置选项中“Agent 使用 TLS 连接”是不是开启的？我试过如果通过TLS连接，好像不可以，此行正想来查找ISSUE中是否有解决方案

好像是这个问题，我把Agent 使用 TLS 连接关闭了就可以了

**Comment by luoli233** [comment]
服务器得手动安装的，你看中文教程
