### ISSUE TITLE
v1.0.22 无法删除被控机

### ISSUE THREAD

**Issue by KKX999** [nezhahq/nezha#563]
### 运行环境

debian 11

### Nezha 版本

v1.0.22

### 描述问题

删除后1-10秒内会复现，无法删除
<img width="1370" alt="屏幕快照 2024-12-06 的 19 18 07 下午" src="https://github.com/user-attachments/assets/d6bdf3fc-5460-4618-b065-38470b590d76">

### 复现步骤

<details></details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
服务停了再删

**Comment by KKX999** [comment]
停止命令是什么

**Comment by KKX999** [comment]
> 服务停了再删
停止命令是什么

**Comment by KKX999** [comment]
> 服务停了再删

停止命令是什么

**Comment by uubulb** [comment]
> > 服务停了再删
> 
> 停止命令是什么

`/opt/nezha/agent/nezha-agent service stop`

**Comment by KKX999** [comment]
好的

UUBulb ***@***.***> 于 2024年12月6日周五 20:42写道：
