### ISSUE TITLE
使用 CloudFlare CDN导致重定向次数过多

### ISSUE THREAD

**Issue by fhb302** [nezhahq/nezha#566]
### 运行环境

Ubuntu24.04

### Nezha 版本

v1.1.2

### 描述问题

<details></details>
使用CloudFlare CDN服务，并使用官方提供的Caddy反代脚本，发现代理后使用 'nc -v' 命令可以显示正常链接，但是网页端访问会出现308错误无法访问页面，在网页控制台中显示不停地重定向

### 复现步骤

<details>CloudFlare已打开CDN，且网络中已设置websocket与grpc开关，服务器已开放8008端口并可通过ip+端口访问</details>
Caddy脚本如下：

```
域名.com {
        @grpcProto {
                path /proto.NezhaService/*
        }

        @websocket {
                path_regexp /api/v1/ws/(server|terminal|file)(.*)
        }

        reverse_proxy @websocket {
                header_up Host {host}
                header_up nz-realip {http.CF-Connecting-IP}
                header_up Origin https://{host}
                header_up Upgrade {http.upgrade}
                header_up Connection "upgrade"

                transport http {
                        read_buffer 16384
                }
                to localhost:8008
        }

        reverse_proxy @grpcProto {
                header_up Host {host}
                header_up nz-realip {http.CF-Connecting-IP}
                transport http {
                        versions h2c
                        read_buffer 4096
                }
                to localhost:8008
        }

        reverse_proxy {
                header_up Host {host}
                header_up Origin https://{host}
                header_up nz-realip {http.CF-Connecting-IP}
                header_up Upgrade {http.upgrade}
                header_up Connection "upgrade"
                transport http {
                        read_buffer 16384
                }
                to localhost:8008
        }
}
```
控制台信息显示如下：
![屏幕截图 2024-12-07 182941](https://github.com/user-attachments/assets/1f55a846-e496-4a06-8816-f9a9830ee162)

使用官方的grpc检测脚本，输出显示 HTTP2/520
使用官方的 "nc -v" 命令，显示：Connection to 域名 (172.67.212.210) 443 port [tcp/https] succeeded!

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by WJHXD1B** [comment]
CloudFlare -> 自定义 SSL/TLS -> **完全**

**Comment by WJHXD1B** [comment]
> ### 运行环境
> Ubuntu24.04
> 
> ### Nezha 版本
> v1.1.2
> 
> ### 描述问题
> 使用CloudFlare CDN服务，并使用官方提供的Caddy反代脚本，发现代理后使用 'nc -v' 命令可以显示正常链接，但是网页端访问会出现308错误无法访问页面，在网页控制台中显示不停地重定向
> ### 复现步骤
> Caddy脚本如下：
> ```
> 域名.com {
>         @grpcProto {
>                 path /proto.NezhaService/*
>         }
> 
>         @websocket {
>                 path_regexp /api/v1/ws/(server|terminal|file)(.*)
>         }
> 
>         reverse_proxy @websocket {
>                 header_up Host {host}
>                 header_up nz-realip {http.CF-Connecting-IP}
>                 header_up Origin https://{host}
>                 header_up Upgrade {http.upgrade}
>                 header_up Connection "upgrade"
> 
>                 transport http {
>                         read_buffer 16384
>                 }
>                 to localhost:8008
>         }
> 
>         reverse_proxy @grpcProto {
>                 header_up Host {host}
>                 header_up nz-realip {http.CF-Connecting-IP}
>                 transport http {
>                         versions h2c
>                         read_buffer 4096
>                 }
>                 to localhost:8008
>         }
> 
>         reverse_proxy {
>                 header_up Host {host}
>                 header_up Origin https://{host}
>                 header_up nz-realip {http.CF-Connecting-IP}
>                 header_up Upgrade {http.upgrade}
>                 header_up Connection "upgrade"
>                 transport http {
>                         read_buffer 16384
>                 }
>                 to localhost:8008
>         }
> }
> ```
> 
> 控制台信息显示如下： ![屏幕截图 2024-12-07 182941](https://private-user-images.githubusercontent.com/10573023/393505302-1f55a846-e496-4a06-8816-f9a9830ee162.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1OTUzMzIsIm5iZiI6MTczMzU5NTAzMiwicGF0aCI6Ii8xMDU3MzAyMy8zOTM1MDUzMDItMWY1NWE4NDYtZTQ5Ni00YTA2LTg4MTYtZjlhOTgzMGVlMTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDE4MTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ODQ3ZDM2NTBmZjM4MzgzZjM1M2JjMDQ5MzJkNzNlZTQ2MTkzZGNiYzMzM2JkNjM5ZWY5NDYyMWFhZjI2NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R7Kam9C2wWkpfsCEevIrF25zjAezIq4esraqWSLhZrI)
> 
> 使用官方的grpc检测脚本，输出显示 HTTP2/520 使用官方的 "nc -v" 命令，显示：Connection to 域名 (172.67.212.210) 443 port [tcp/https] succeeded!
> 
> ### 附加信息
> ### 验证
> * [x]  我确认这是一个 nezha (哪吒面板) 的问题。
> * [x]  我已经搜索了 Issues，并确认该问题之前没有被反馈过。

CloudFlare -> 自定义 SSL/TLS -> **完全**
