### ISSUE TITLE
Linux OpenWrt 6.6.63 提示文件的格式不正确

### ISSUE THREAD

**Issue by zsanjin-p** [nezhahq/nezha#577]
### 运行环境

Linux OpenWrt 6.6.63 #0 SMP Wed Dec  4 09:55:43 2024 aarch64 GNU/Linux

### Nezha 版本

1.1.3，0.20.5

### 描述问题

按照https://nezha.wiki/guide/agent.html指南，安装openwrt的探针

[root@OpenWrt:12:55 AM ~] # uname -m
aarch64

[root@OpenWrt:12:59 AM ~] # wget -O nezha-agent.zip https://github.com/nezhahq/agent/releases/latest/download/nezha-agent_linux_arm.zip

配置好后运行显示
[root@OpenWrt:01:05 AM ~] # /etc/nezha/nezha-agent -c /etc/nezha/config.yml
-bash: /etc/nezha/nezha-agent: cannot execute binary file: Exec format error

### 复现步骤

同问题描述

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by U201413497** [comment]
aarch64 GNU/Linux，[linux_arm.zip]

你自己下载错了。arm默认是32为，arm64才是64位。

**Comment by zsanjin-p** [comment]
确实是要64位
