### ISSUE TITLE
从V0升级上来。admin 用户名和密码不对，出现Api error unauthorized? 请求解决。下面有日志

### ISSUE THREAD

**Issue by sunteta** [nezhahq/nezha#578]
### 运行环境

ubuntu 20

### Nezha 版本

v1

### 描述问题

<details>[0.212ms] [rows:0] SELECT `id`,`password` FROM `users` WHERE username = "admin" ORDER BY `users`.`id` LIMIT 1

[GIN] 2024/12/11 - 09:28:12 | 200 |     368.916µs |  x.x.x.x | POST     "/api/v1/login"

2024/12/11 09:28:12 github.com/nezhahq/nezha/cmd/dashboard/controller/jwt.go:91 record not found</details>

### 复现步骤

<details>docker 安装。同时自动删除了 v0的docker , 节点数据有自动加上。登录时出错</details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by mr-dragon** [comment]
删掉：/opt/nezha/dashboard/data	下的 sqlite.db后重启
