### ISSUE TITLE
后台删除一个机，过几秒又会出现

### ISSUE THREAD

**Issue by vbskycn** [nezhahq/nezha#586]
### 运行环境

ubuntu22.04

### Nezha 版本

1.14

### 描述问题

<details></details>
后台删除一个机，过几秒又会出现

### 复现步骤

<details></details>
后台删除一个机，过几秒又会出现

### 附加信息

<details></details>
删除按钮意义就不大了

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by Silentely** [comment]
curl -L https://raw.githubusercontent.com/nezhahq/scripts/main/agent/install.sh -o agent.sh && chmod +x agent.sh && ./agent.sh uninstall

**Comment by uubulb** [comment]
Duplicate of https://github.com/nezhahq/nezha/issues/563
