### ISSUE TITLE
建议增加面板访问密码

### ISSUE THREAD

**Issue by Herissmon** [nezhahq/nezha#725]
### 运行环境

centos 7 x86_64

### Nezha 版本

V1

### 描述问题

<details></details>
很简单，和v0一样，增加面板的访问密码，这样能较好的保护隐私

### 复现步骤

<details></details>
无

### 附加信息

<details></details>
无

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
Duplicate of https://github.com/nezhahq/nezha/issues/572
