### ISSUE TITLE
增加主题

### ISSUE THREAD

**Issue by Herissmon** [nezhahq/nezha#726]
### 运行环境

centos 7 x86_64

### Nezha 版本

V1

### 描述问题

<details></details>
增加更多主题，现在自带主题都没得选，就2个
![Screenshot_20241214_174840](https://github.com/user-attachments/assets/9bee04a4-d350-44d5-bd3c-321dbd3556e9)

### 复现步骤

<details></details>
无

### 附加信息

<details></details>
希望能把v0的主题迁移过来 谢谢

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
原来的主题大多数都有点跟不上时代了，比如hotaru已经是三朝老兵了
现在新的默认主题我个人认为算是个好的开始，用的热门框架，开发也比之前规范不少
serverstatus 主题的作者已经不再活跃，如果不是呼声特别高的话 应该没人移植.
