### ISSUE TITLE
panic: yaml: invalid trailing UTF-8 octet

### ISSUE THREAD

**Issue by lammy2021** [nezhahq/nezha#872]
### 运行环境

Ubuntu LTS 22

### Nezha 版本

last

### 描述问题

<details>
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
panic: yaml: invalid trailing UTF-8 octet

goroutine 1 [running]:
github.com/nezhahq/nezha/service/singleton.InitConfigFromPath(...)
	github.com/nezhahq/nezha/service/singleton/singleton.go:64
main.main()
	github.com/nezhahq/nezha/cmd/dashboard/main.go:108 +0x70f
</details>

### 复现步骤

<details>
使用curl -L https://raw.githubusercontent.com/nezhahq/scripts/refs/heads/main/install.sh -o nezha.sh && chmod +x nezha.sh && sudo ./nezha.sh安装面板，docker安装
</details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by GilHogan** [comment]
怎么解决的啊

**Comment by lammy2021** [comment]
> 怎么解决的啊

忘记了，但是我重新安装了几次就可以了
