### ISSUE TITLE
后台设置服务不生效

### ISSUE THREAD

**Issue by mzit** [nezhahq/nezha#917]
### 运行环境

Ubuntu 22.04.5 LTS (GNU/Linux 5.15.0-124-generic x86_64)

### Nezha 版本

1.4.5

### 描述问题

在后台设置了延迟监控后，在前端面板页面上能看到监控项，但是一直没有数据

### 复现步骤

<img width="1018" alt="image" src="https://github.com/user-attachments/assets/8d8af766-a3fb-482c-8779-7816d85d15d5" />
<img width="555" alt="image" src="https://github.com/user-attachments/assets/334a3208-ec69-4b78-93cb-473d5c95c1e0" />
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/32fd48c7-d552-4117-8309-e0649328e086" />

### 配置信息

<details></details>

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by z6211563** [comment]
我新添加的服务监控也是这样
