### ISSUE TITLE
在自定义代码栏中添加代码并保存后未生效，刷新页面后代码会消失

### ISSUE THREAD

**Issue by wefun8** [nezhahq/nezha#924]
### 运行环境

Debian12

### Nezha 版本

1.4.9

### 描述问题

<details>在管理面板自定义代码（样式和脚本）栏中添加美化代码，只添加一行代码时能够生效，但是当添加超过两行代码在确认并刷新页面后代码会消失。</details>

### 复现步骤

<details>
例如添加下面这一行代码可以生效：
<script src="https://cdn.jsdelivr.net/gh/mocchen/cssmeihua/js/aixin.js"></script>
但是当添加类似下面的两行以上代码时，效果不会生效，点击确认提示成功，刷新页面后代码会消失：
<script src="https://cdn.jsdelivr.net/gh/mocchen/cssmeihua/js/aixin.js"></script>
<script src="https://cdn.jsdelivr.net/gh/mocchen/cssmeihua/js/yinghua.js"></script>
</details>

### 配置信息

<details></details>
 

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by ZhaoSunrise-Lee** [comment]
我也遇见这个问题
